name: Build executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed \
            --icon=./strong_random_password_generator.icns \
            --name="Strong Random Password Generator" \
            --paths=./strong_random_password_generator \
            strong_random_password_generator/main.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ runner.os }}-executable
          path: |
            dist/*
